### PR TITLE
maintenance

### PR DESCRIPTION
**Pull request by TacoTheDank**
- target android pie
- java 1.8 compatibility
- bump kotlin to 1.2.71 (1.3.0 is released; I'll let you do that :))
- use kotlin jdk8
- replaced some kotlin "if"s with "when"s
- reformat code
- fix some english

### CODE REVIEW

**Comment by 42SK** [comment]
Great, thanks a lot!
I just had a brief look at your changes, and they all seem like really good ideas.
I'm currently on the road, so I'll probably merge this sometime next week once I've had the time to give it a more thorough examination (in other words: once I've checked that everything works ;-) ).
Once again, huge thanks for your contribution!

**Comment by TacoTheDank** [comment]
I'm glad you like it haha, thank you!

**Comment by 42SK** [comment]
OK, since this is a rather miscellaneous pull request, I decided to add your changes to the master branch individually (as opposed to just merging everything at once).
Most of the changes you proposed have already been added, however, I'll probably suspend all changes regarding the build files until the next major release, so that we can do some more thorough testing after updating the Kotlin libraries, etc..
Once again, thanks for your contribution!

**Comment by TacoTheDank** [comment]
That's alright, thanks! :D

**Pull request closed without merging**
