### PR TITLE
Improvments

### PR DESCRIPTION
**Pull request by l-jonas**
- adjusted for new Android Studio Version
- adjusted for Android 8
- simpler UI
  - this removes the possibility of a brand selection for the infinite mode
  - remove transmission dialog
  - show progress bar when sending all off patterns
  - show other app content instead of dialog when device is not supported
- refactored widget
  - widget indicates if currently sending + allows canceling
- move all transmission work into a Service
  - the screen rotation lock is not needed anymore

### CODE REVIEW

**Comment by Elegary** [comment]
Your design is cool :)
But you don't keep the feature of transmitting ir code of specific brand.

**Comment by l-jonas** [comment]
@Elegary It's still there. There is a button at the Toolbar/ Action Bar for it.

**Comment by Elegary** [comment]
Yes, I saw it, but I can't select a specific brand for **repetitive mode**.

**Comment by 42SK** [comment]
OK, wow!
This is quite a huge set of changes.
Fist of all, thanks a lot for putting so much time and effort into TVKILL, I really appreciate it.
Now, since this is obviously a very large (and significant) PR, I'll try to summarize my thoughts on the individual changes as briefly as possible:
- General backend-related changes
  - Updating the Android build-tools, gradle, etc. (a.k.a. "Adjust for new Android Studio Version")
-> This is something that was probably long overdue. It's nice that somebody has finally managed to take care of this.
  - Rewriting several several components in Kotlin
-> I'm not quite sure why anyone would would deliberately choose Kotlin over Java in a largely Java based project, given the fact that the benefits are rather insignificant. However, since Kotlin is definitely way cooler than Java, I guess this is quite a nice Idea.

- UI changes
-> Since improvements on the UI are always of a rather subjective nature, I can only try to convey my personal opinion on this.
  - Removing the brand selection option from the infinite mode.
-> Removing features is generally not one of the best Ideas; Since a lot of users (including myself) use this option to speed up the infinite mode, I'd strongly suggest that we try to retain it.
  - Display a progress bar when sending all off patterns
-> This is a great idea! I had already thought about this a while ago, but I never managed to implement it. Good job!
  - Removing the transmission dialog
-> This is (of course) a logical step to take since we now have a progress bar. However, I think it wouldn't be such a bad idea to display some form of text that tells the user what the app is currently doing, so that new user don't get too confused.
  - Removing the help dialogs
-> Speaking of new users: For some reason, you removed all the help dialogs. In my opinion, this is an essential feature to anyone who has not yet used the app and is looking for an explanation on how to use it. We really should keep this!
  - Show a fragment instead of dialog when device is not supported
-> I don't really see the benefit in this, but if you think that this is important, I see no reason why we can't change it.
  - New widget 
-> Judging by your comment, this sounds like quite an interesting improvement. However, I tested this on two different devices (Android 6.0) and on both of them, the widget didn't work (neither did the IR blaster transmit anything, nor was there any visual indication that the app was transmitting). Maybe we should have another look at this?
 
Right now, I still have to review most of your code before I can merge it.
While I really like the fact that you've obviously worked quite hard to contribute to this project, I still have some doubts about the UI changes. Especially the missing help dialogs and the removal of the brand selection option make things a lot harder.
Even thought I think that some of your ideas (like the progress bar) are really cool, I'm not sure whether or not I should merge this PR as a whole, since for most users the benefits don't necessarily outweigh the losses.
However, I could very much think of integrating some of your improvements into the current UI of the App (e.g. one could add a "cancel" button and a progress bar to the transmission dialog or replace the current brand fragment with your version).

Once again, huge thanks for your contribution,
I hope that we can somehow find a way to put it to good use without upsetting any existing users. Until then, any opinions or comments on the new Interface are highly appreciated!

**Comment by l-jonas** [comment]
@Elegary I said that already that this is not possible anymore.
@42SK I will re-add the brand selection for the infinite mode. Should it be a single selection (as it was) or a multi selection? Should the selection be saved or reseted when the App is opened again?

On Android 8, I had to force kill the App "TV Kill" until a newly added widget worked. I will look again into this.

To the help dialogs: I think the help dialogs are not needed because it's relative obvious what the screens do. Correct me If i'm wrong.

**Comment by 42SK** [comment]
@l-jonas 

> I will re-add the brand selection for the infinite mode. Should it be a single selection (as it was) or a multi selection? Should the selection be saved or reseted when the App is opened again?

I had also already thought about a multi selection for the infinite mode. However, since the standard use case for the brand selection would be that the user knows his TV's brand and simply wants to keep turning it of whenever it is switched back on, I guess a single selection would also do just fine.
(By the way, how exactly do you intend to re-implement this now that the infinite and the universal mode are in the same fragment?)

> On Android 8, I had to force kill the App "TV Kill" until a newly added widget worked. I will look again into this.

 OK, that indeed solved the issue I was having on my devices. I *really* like the new widget design, good job!

> To the help dialogs: I think the help dialogs are not needed because it's relative obvious what the screens do. Correct me If i'm wrong.

Your actually not that wrong, it is *relatively* obvious what the screens do. To long term users (like you and me), everything might seem rather intuitive, but new users are probably a bit confused at first (especially since we now have no clear distinction between the infinite mode and the universal mode). In addition to that, the help dialogs also explain how the app actually *works* (transmitting patterns sequentially, continuously transmitting even when the app is closed in infinite mode, etc.); since this information simply cannot be conveyed through a UI, I do think that there is quite a significant need for some form of documentation. I would suggest that we simply move the old help texts to an extra "help fragment". We could use the old dialog titles as headers for subsections through which the user can browse.

> To the removing the transmission dialog: I think it's easy to see that the App is running (because the send button transforms into a stop button)/ all other buttons are disabled. But I don't like texts. Eventually the progress bar could always be shown (with the infinite animation).

Here's a suggestion, we could move the "repetitive mode" check-box up a bit and display a small "transmitting…" text directly above the progress bar, just to make it unequivocally clear what the progress bar is actually indicating. Again, I don't want to have new users guessing what the app is currently doing, and a small text can accomplish a lot in this regard (we could also use a different text when the repetitive mode is used to make the distinction more obvious).
I like the idea of showing the infinite animation, we should definitely consider adding this sooner or later.

Meanwhile, I still have a few questions regarding your changes:
- The mute and the off button tend to obscure one another in the main fragment, is this the intended behavior?
- The mute and off buttons in the brands fragment don't really look like "buttons", since they are simply text in a list view; perhaps we should change this so that they look a bit more "clickable"?
(Also, since the individual items in the list are rather large now, we could also replace the "off" and "mute" text with the corresponding icon (this might be a good idea given the fact that you apparently don't like text ;-) ).
- Why did you remove the screen rotation lock?
The purpose of this was to prevent the screen from rotating whenever the user holds his phone in an "unconventional" position while aiming at a TV.

**Comment by l-jonas** [comment]
@Elegary @42SK The infinite mode was added to the brand screen (a CheckBox in top of the list like at the universal screen). A multi selection is not implemented.

@42SK It was a bug of mine that it was required to kill the app until the widgets work. This is fixed now.

Your suggestion for the help screen is an good idea. I will do it this way.

I will add the "transmitting" text as suggested (but I will add the icon for remote: https://material.io/tools/icons/?search=remote&style=baseline)

The "intended" (current) behaviour (at my device) is that the active (running or touched) button is in the front. Otherwise, the mute button is in the front. I can move the mute button away from the power button, but I think it looks a bit better this way (I have absolutly nothing against changing that).

The buttons in the brand list are flat material buttons. The text style shows it. But yes, icons would fit better (brand in the left, icons in the right, all at the same height).

The screen rotation lock was removed because it's technically not needed anymore (the App has got no problem with configuration changes because the transmission happens in a Service). If it's for usabillity reasons, I will readd it.

**Comment by 42SK** [comment]
> Your suggestion for the help screen is an good idea. I will do it this way.

Great!
 
> I will add the "transmitting" text as suggested (but I will add the icon for remote: https://material.io/tools/icons/?search=remote&style=baseline)

What exactly do you mean by "add the icon for remote"?  And perhaps you could reuse the existing "transmitting" strings from the old version so that we can keep the translations.

> The "intended" (current) behavior (at my device) is that the active (running or touched) button is in the front. Otherwise, the mute button is in the front. I can move the mute button away from the power button, but I think it looks a bit better this way

Since this is intended and you think it looks better, I suggest we simply keep it that way.

> The screen rotation lock was removed because it's technically not needed anymore (the App has got no problem with configuration changes because the transmission happens in a Service). If it's for usabillity reasons, I will readd it.

Yes, this is purely for usability.

**Comment by l-jonas** [comment]
@42SK 

Help screen is implemented.

The strings were reused. However, there is the new string "help" (title of the menu item and the screen itself). There wasn't anything like that earlier (because there was only a icon).

The UI is

```
icon            transmitting ...
icon            progress bar....
```

You can see it when you run it.

The screen rotation lock was readded.

**Comment by 42SK** [comment]
Alright, I really like the way this is going.
One last comment: perhaps we should grayed out the mute option in the brand tab when the repetitive option is checked, since repetitively sending mute patterns wouldn't make that much sense.

**Comment by l-jonas** [comment]
@42SK Muting is disabled (with explaination) when the repetitive mode is on. However, this does not happen in the universal mode (there's no good location for an explaination).

The settings screen was refactored. Due to that, the delay between patterns from old versions is resetted with this one (but it can be configured again).

I also resolved somehow https://github.com/42SK/TVKILL/issues/11 by allowing to show the currently transmitted brand (with the number of the pattern if it's not the first one).

**Comment by 42SK** [comment]
@l-jonas 
Why should it be a good idea to completely reimplemented the settings screen?
In addition to being unnecessary, your implementation is also rather bizarre.
You somehow managed to reimplemented check boxes using image views, added a very bloated Fragment that actually adds an extra method for every single preference, instead of just using **any** of [the standard APIs](https://developer.android.com/guide/topics/ui/settings).
This is definitely not good practice.
Thus, I am merely going to merge everything *before* this strange commit (e532593), meaning that I am also excluding all changes regarding Issue #11. While extending the UI so that it also displays the name of brand who's pattern is currently being transmitted remains a good idea, we must find a different way to implement this.
I should also point out that I am merging this into a new branch, which we can then merge into the master branch once the new UI is proven to be mature enough for deployment.

**Comment by 42SK** [comment]
@l-jonas 
>The usage of Images instead of CheckBoxes was required to make the title and the subtitle clickable to change the value.

Why would anyone want a CheckBox to change its state when something other that the checkbox is clicked? The idea of implementing this using ImageViews is perhaps even more baffling. Even if one  where to desire such a peculiar UI, one could simply use `Checkable.setChecked`.

>The extra methods for everything add type safety so that it's not possible to make a typo which would result in no effect of the setting.

Type safety would not be of any concern at all if one simply where to use the standard APIs.

> But please note that the way you used it (PreferenceActivity.addSharedPreferencesFromXml) is deprecated.

Yes, you are right, this method is deprecated, but only because Activities as a whole have been mostly replaced by Fragments (and **not** because it is now common practice to implement CheckBoxes using ImageViews) . Hence, one is now simply supposed to to use [`PreferenceFragmentCompat.setPreferencesFromResource`](https://developer.android.com/reference/android/support/v7/preference/PreferenceFragmentCompat#setPreferencesFromResource(int,%20java.lang.String)).

Finally, the main question still remains: Why should it be necessary to reimplemented the preferences in the first place? If I understand it correctly, you were *actually* tying to fix issue #11, which should not require any tampering with the preferences whatsoever.

> You could do a partital rollout in Google Play or use the beta channel there. Or how do you want to test how good/ bad the UI is?

Yes, I am planing to do a partial roll-out on Google Play sooner or later, but first, I must finish  reviewing your code and make sure that everything works properly.

**Comment by 42SK** [comment]
@l-jonas 
Yes, if you want, you can implement this in a way that does not interfere with the settings screen.
You can simply add your settings option to the `preferences.xml` file.
It is important that we keep the current interface of the settings screen since it provides a user experience that is consistent with the default Android UI.

**Comment by l-jonas** [comment]
@42SK I KNOW how to use the standard settings system. IF I wouldn't know it, I wouldn't say that I don't like it.

**Pull request closed without merging**
